// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0UyLXGFJumauKr6QA4Sbt8FZe3oBEQMc',
    appId: '1:402179568585:web:f0ed40a0b914f751f3ee18',
    messagingSenderId: '402179568585',
    projectId: 'movieloverv2',
    authDomain: 'movieloverv2.firebaseapp.com',
    storageBucket: 'movieloverv2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsPDL1XYwZNZtMpa0ajk79ETNP9m0yurY',
    appId: '1:402179568585:android:7a3da62307787813f3ee18',
    messagingSenderId: '402179568585',
    projectId: 'movieloverv2',
    storageBucket: 'movieloverv2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATPPLN0yjj54YspcKj8-rDBkFzfS_Ffpc',
    appId: '1:402179568585:ios:cae82496c5910708f3ee18',
    messagingSenderId: '402179568585',
    projectId: 'movieloverv2',
    storageBucket: 'movieloverv2.appspot.com',
    iosBundleId: 'com.example.sun3tolineDevMovielover',
  );
}
